import type { Locale } from "./messages";

type LegalPageContent = {
  title: string;
  sections: [string, string][];
  back: string;
  contact?: string;
};

export const cookiesContent = {
  fr: { title: "Politique de cookies", sections: [["Qu'est-ce qu'un cookie ?", "Un cookie est un petit fichier texte déposé sur votre appareil lors de la visite d'un site. Il permet de mémoriser vos préférences et d'améliorer votre expérience."], ["Quels cookies utilisons-nous ?", "Cookies essentiels — nécessaires au fonctionnement du site (session, sécurité). Cookies de préférences — mémorisent vos choix (langue, thème sombre/clair). Cookies analytiques — nous aident à comprendre comment le site est utilisé (Google Analytics, etc.)."], ["Comment gérer vos cookies ?", "Vous pouvez à tout moment modifier votre choix en cliquant sur le lien « Gérer les cookies » en bas de page, ou directement depuis les paramètres de votre navigateur."], ["Durée de conservation", "Votre choix (accepter ou refuser) est conservé pendant 6 mois dans votre navigateur via localStorage. Passé ce délai, la bannière réapparaîtra."], ["Contact", "Pour toute question :"]], back: "← Retour à l'accueil", contact: "contact@onabaya.ci" },
  en: { title: "Cookie policy", sections: [["What is a cookie?", "A cookie is a small text file stored on your device when you visit a website. It remembers your preferences and improves your experience."], ["Which cookies do we use?", "Essential cookies — required for the site to work (session, security). Preference cookies — remember your choices (language, light or dark theme). Analytics cookies — help us understand how the site is used (Google Analytics, etc.)."], ["How can you manage cookies?", "You can change your choice at any time by clicking the « Manage cookies » link at the bottom of the page, or through your browser settings."], ["Retention period", "Your choice (accept or decline) is stored in your browser through localStorage for 6 months. The banner will reappear after that period."], ["Contact", "For any questions:"]], back: "← Back to home", contact: "contact@onabaya.ci" },
  es: { title: "Política de cookies", sections: [["¿Qué es una cookie?", "Una cookie es un pequeño archivo de texto que se guarda en tu dispositivo al visitar un sitio web. Permite recordar tus preferencias y mejorar tu experiencia."], ["¿Qué cookies utilizamos?", "Cookies esenciales — necesarias para el funcionamiento del sitio (sesión y seguridad). Cookies de preferencias — recuerdan tus opciones (idioma y tema claro u oscuro). Cookies analíticas — nos ayudan a entender cómo se utiliza el sitio (Google Analytics, etc.)."], ["¿Cómo puedes gestionar las cookies?", "Puedes cambiar tu elección en cualquier momento haciendo clic en « Gestionar cookies » al final de la página o desde la configuración de tu navegador."], ["Duración de conservación", "Tu elección (aceptar o rechazar) se guarda durante 6 meses en tu navegador mediante localStorage. Después, el banner volverá a aparecer."], ["Contacto", "Para cualquier pregunta:"]], back: "← Volver al inicio", contact: "contact@onabaya.ci" },
} satisfies Record<Locale, LegalPageContent>;

export const privacyContent = {
  fr: { title: "Politique de confidentialité", sections: [["1. Qui sommes-nous ?", "Onabaya SARL est une société immatriculée en Côte d'Ivoire, exploitant la plateforme Onabaya. Nous sommes le responsable du traitement de vos données personnelles."], ["2. Quelles données collectons-nous ?", "Données d'inscription (nom, email, téléphone, ville et rôle), données de profil (photo, description, notes et avis), données de transaction (commandes, paiements et litiges), données de localisation avec votre consentement, et données techniques (adresse IP, navigateur, appareil et cookies)."], ["3. Pourquoi collectons-nous ces données ?", "Nous les utilisons pour fournir et améliorer nos services, sécuriser les transactions, suivre les livraisons, communiquer avec vous et respecter nos obligations légales."], ["4. Qui a accès à vos données ?", "Vos données sont accessibles à l'équipe Onabaya, aux utilisateurs concernés uniquement pour la transaction, et à nos prestataires techniques sous contrat de confidentialité."], ["5. Combien de temps conservons-nous vos données ?", "Vos données sont conservées pendant la durée d'activité de votre compte. Après sa suppression, elles sont anonymisées ou supprimées dans un délai de 12 mois, sauf obligation légale."], ["6. Vos droits", "Vous disposez d'un droit d'accès, de rectification, d'effacement, de portabilité et d'opposition. Pour exercer ces droits, contactez-nous à :"], ["7. Sécurité", "Nous mettons en œuvre des mesures techniques et organisationnelles pour protéger vos données : chiffrement SSL, authentification sécurisée, sauvegardes régulières et accès restreint."], ["8. Modifications", "Cette politique peut être mise à jour à tout moment. Les modifications significatives vous seront notifiées par email ou via l'application."], ["9. Contact", "Pour toute question relative à vos données :"]], back: "← Retour à l'accueil", contact: "privacy@onabaya.ci" },
  en: { title: "Privacy policy", sections: [["1. Who are we?", "Onabaya SARL is a company registered in Côte d'Ivoire operating the Onabaya platform. We are responsible for processing your personal data."], ["2. What data do we collect?", "Registration data (name, email, phone number, city and role), profile data (photo, description, ratings and reviews), transaction data (orders, payments and disputes), location data with your consent, and technical data (IP address, browser, device and cookies)."], ["3. Why do we collect this data?", "We use it to provide and improve our services, secure transactions, track deliveries, communicate with you and meet our legal obligations."], ["4. Who can access your data?", "Your data is accessible to the Onabaya team, other users only when necessary for a transaction, and technical providers bound by confidentiality agreements."], ["5. How long do we keep your data?", "Your data is kept while your account is active. After deletion, it is anonymized or deleted within 12 months unless the law requires otherwise."], ["6. Your rights", "You may request access, correction, deletion, portability or object to certain processing. To exercise these rights, contact us at:"], ["7. Security", "We use technical and organizational measures to protect your data, including SSL encryption, secure authentication, regular backups and restricted access."], ["8. Changes", "This policy may be updated at any time. Significant changes will be notified by email or through the app."], ["9. Contact", "For any questions about your data:"]], back: "← Back to home", contact: "privacy@onabaya.ci" },
  es: { title: "Política de privacidad", sections: [["1. ¿Quiénes somos?", "Onabaya SARL es una empresa registrada en Costa de Marfil que gestiona la plataforma Onabaya. Somos responsables del tratamiento de tus datos personales."], ["2. ¿Qué datos recopilamos?", "Datos de registro (nombre, email, teléfono, ciudad y rol), datos de perfil (foto, descripción, valoraciones y opiniones), datos de transacciones (pedidos, pagos y conflictos), datos de ubicación con tu consentimiento y datos técnicos (IP, navegador, dispositivo y cookies)."], ["3. ¿Por qué recopilamos estos datos?", "Los utilizamos para prestar y mejorar nuestros servicios, proteger las transacciones, seguir las entregas, comunicarnos contigo y cumplir nuestras obligaciones legales."], ["4. ¿Quién puede acceder a tus datos?", "Tus datos son accesibles para el equipo de Onabaya, otros usuarios solo cuando sea necesario para una transacción y proveedores técnicos sujetos a confidencialidad."], ["5. ¿Cuánto tiempo conservamos tus datos?", "Conservamos tus datos mientras tu cuenta esté activa. Tras eliminarla, los anonimizamos o eliminamos en un plazo de 12 meses, salvo obligación legal."], ["6. Tus derechos", "Puedes solicitar el acceso, la rectificación, la eliminación o la portabilidad de tus datos, así como oponerte a ciertos tratamientos. Para ejercerlos, escríbenos a:"], ["7. Seguridad", "Aplicamos medidas técnicas y organizativas para proteger tus datos, como cifrado SSL, autenticación segura, copias de seguridad y acceso restringido."], ["8. Cambios", "Esta política puede actualizarse en cualquier momento. Te avisaremos de los cambios importantes por email o mediante la aplicación."], ["9. Contacto", "Para cualquier pregunta sobre tus datos:"]], back: "← Volver al inicio", contact: "privacy@onabaya.ci" },
} satisfies Record<Locale, LegalPageContent>;

export const legalNoticeContent = {
  fr: { title: "Mentions légales", sections: [["Éditeur du site", "Le site Onabaya est édité par la société Onabaya SARL, immatriculée au RCCM de Cotonou sous le numéro BJ-COT-XXXXX-X. Siège social : Cotonou, Bénin. Email : contact@onabaya.bj. Téléphone : +229 00 00 00 00"], ["Directeur de la publication", "DOHOU Gbênoupko Fawase / CEO, en qualité de Directeur de la publication."], ["Hébergement", "Le site est hébergé par [Nom de l'hébergeur], dont le siège social est situé à [Adresse de l'hébergeur]."], ["Propriété intellectuelle", "L'ensemble du contenu du site Onabaya (textes, images, logos, interface et code source) est la propriété exclusive d'Onabaya SARL, sauf mention contraire. Toute utilisation sans autorisation écrite préalable est interdite."], ["Activité", "Onabaya est une plateforme de mise en relation numérique dédiée au commerce de produits vivriers en Côte d'Ivoire. Elle agit comme intermédiaire technique entre les parties."], ["Crédits", "Icônes : Lucide Icons (licence MIT). Design et développement : Équipe Onabaya."]], back: "← Retour à l'accueil" },
  en: { title: "Legal notice", sections: [["Website publisher", "The Onabaya website is published by Onabaya SARL, registered with the Cotonou RCCM under number BJ-COT-XXXXX-X. Registered office: Cotonou, Benin. Email: contact@onabaya.bj. Phone: +229 00 00 00 00"], ["Publication director", "DOHOU Gbênoupko Fawase / CEO, acting as publication director."], ["Hosting", "The website is hosted by [Host name], whose registered office is located at [Host address]."], ["Intellectual property", "All content on the Onabaya website (text, images, logos, interface and source code) belongs exclusively to Onabaya SARL unless stated otherwise. Any use without prior written permission is prohibited."], ["Business activity", "Onabaya is a digital matchmaking platform for the food-product trade in Côte d'Ivoire. It acts as a technical intermediary between the parties."], ["Credits", "Icons: Lucide Icons (MIT license). Design and development: Onabaya team."]], back: "← Back to home" },
  es: { title: "Aviso legal", sections: [["Editor del sitio", "El sitio web de Onabaya está publicado por Onabaya SARL, registrada en el RCCM de Cotonú con el número BJ-COT-XXXXX-X. Domicilio social: Cotonú, Benín. Email: contact@onabaya.bj. Teléfono: +229 00 00 00 00"], ["Director de la publicación", "DOHOU Gbênoupko Fawase / CEO, como director de la publicación."], ["Alojamiento", "El sitio está alojado por [Nombre del proveedor], con domicilio social en [Dirección del proveedor]."], ["Propiedad intelectual", "Todo el contenido del sitio de Onabaya (textos, imágenes, logotipos, interfaz y código fuente) pertenece exclusivamente a Onabaya SARL, salvo indicación contraria. Está prohibido utilizarlo sin autorización escrita previa."], ["Actividad", "Onabaya es una plataforma digital de conexión para el comercio de alimentos en Costa de Marfil. Actúa como intermediario técnico entre las partes."], ["Créditos", "Iconos: Lucide Icons (licencia MIT). Diseño y desarrollo: equipo de Onabaya."]], back: "← Volver al inicio" },
} satisfies Record<Locale, LegalPageContent>;
