import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/shared/navbar";
import FooterSection from "@/components/shared/footer";
import CookieBanner from "@/components/ux/CookieBanner";
import LocaleProvider from "@/components/providers/locale-provider";
import { myCustomFont, SatoshiCustomFont, TankerCustomFont, DancingCustomFont } from "@/lib/font";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased ${myCustomFont.variable}   ${SatoshiCustomFont.variable} ${TankerCustomFont.variable} ${DancingCustomFont.variable}`}
    >
      <body className="min-h-full flex flex-col ">
        <LocaleProvider>
          <Navbar />
          {children}
          <CookieBanner />
          <FooterSection />
        </LocaleProvider>
      </body>
    </html>
  );
}
